-- MySQL Script generated by MySQL Workbench
-- Sat Apr  2 19:41:18 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema onlinetesting
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema onlinetesting
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `onlinetesting` DEFAULT CHARACTER SET utf8 ;
USE `onlinetesting` ;

-- -----------------------------------------------------
-- Table `onlinetesting`.`tests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlinetesting`.`tests` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `nameOfDiscipline` VARCHAR(50) NOT NULL,
  `difficulty` INT NOT NULL,
  `time_minutes` INT NOT NULL,
  `countOfQuestions` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 107
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `onlinetesting`.`questions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlinetesting`.`questions` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tests_id` INT NOT NULL,
  `question` VARCHAR(150) NOT NULL,
  `questionNumber` INT NOT NULL,
  PRIMARY KEY (`id`, `tests_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_questions_tests1_idx` (`tests_id` ASC) VISIBLE,
  CONSTRAINT `fk_questions_tests1`
    FOREIGN KEY (`tests_id`)
    REFERENCES `onlinetesting`.`tests` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 182
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `onlinetesting`.`answers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlinetesting`.`answers` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `answer` VARCHAR(150) NOT NULL,
  `isRightAnswer` TINYINT NOT NULL,
  `questions_id` INT NOT NULL,
  PRIMARY KEY (`id`, `questions_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_answers_questions1_idx` (`questions_id` ASC) VISIBLE,
  CONSTRAINT `fk_answers_questions1`
    FOREIGN KEY (`questions_id`)
    REFERENCES `onlinetesting`.`questions` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 459
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `onlinetesting`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlinetesting`.`roles` (
  `idroles` INT NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idroles`),
  UNIQUE INDEX `rolescol_UNIQUE` (`role` ASC) VISIBLE,
  UNIQUE INDEX `idroles_UNIQUE` (`idroles` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `onlinetesting`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlinetesting`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `login` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `salt` VARCHAR(20) NOT NULL,
  `name` VARCHAR(30) NOT NULL,
  `surname` VARCHAR(30) NOT NULL,
  `blocked` TINYINT NOT NULL,
  `id_role` INT NOT NULL,
  PRIMARY KEY (`id`, `id_role`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC) VISIBLE,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `fk_users_roles1_idx` (`id_role` ASC) VISIBLE,
  CONSTRAINT `fk_users_roles1`
    FOREIGN KEY (`id_role`)
    REFERENCES `onlinetesting`.`roles` (`idroles`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `onlinetesting`.`passedtests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `onlinetesting`.`passedtests` (
  `user_id` INT NOT NULL,
  `test_id` INT NOT NULL,
  `mark` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`test_id`, `user_id`),
  INDEX `fk_passedTests_users_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_passedTests_tests1_idx` (`test_id` ASC) VISIBLE,
  CONSTRAINT `fk_passedTests_tests1`
    FOREIGN KEY (`test_id`)
    REFERENCES `onlinetesting`.`tests` (`id`),
  CONSTRAINT `fk_passedTests_users`
    FOREIGN KEY (`user_id`)
    REFERENCES `onlinetesting`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
